### ISSUE TITLE
I'm not sure how to run this

### ISSUE THREAD

**Issue by joawesome** [konsgn/BlueMagic#3]
I am quit unsure on how to run this on the bluepill. I dont really know how to get a bootloader to run the bin file on the bluepill. I'm sorry but i'm quit inexperienced to this

**Comment by konsgn** [comment]
Follow along with this guide for programming a Bluepill into a Blackmagic probe:
https://paramaggarwal.medium.com/converting-an-stm32f103-board-to-a-black-magic-probe-c013cf2cc38c

Stop when you get to the dfu-util section. Instead of the ~~`dfu-util -d 1d50:6018,:6017 -s 0x08002000:leave -D blackmagic.bin`~~ command , load instead the bluemagic.bin file:
`dfu-util -d 1d50:6018,:6017 -s 0x08002000:leave -D bluemagic.bin`
Then hookup to your target via the pinout table and you will be good to go once dfu-util succeeds and you restart the bluepill.

BTW, Be **Carefull** with voltages, Make sure that your target supports 3.3v operation. Most do, but you could damage a csr chip that runs @ 1.8V without a voltage translator between devices. Blackmagic probes have this, but the the BluePill dev board doesn't.

**Comment by joawesome** [comment]
Alright thank you! i will try to attempt this later on and see how it goes

**Comment by konsgn** [comment]
Good Luck!
